feat: implemented delegate methods
apphud/ApphudSDK-React-Native pull request #11
Opened 2021-04-08 19:36 UTC by alexandr-makarov-am

2021-04-12 10:51 UTC, ren6 requested changes

2021-04-12 10:51 UTC, ren6 commented on src/ApphudSdkType.ts
> +export interface AttributeProperties {
переименуй плиз AttributionProperties

2021-04-12 10:51 UTC, ren6 commented on src/ApphudSdkType.ts
> +  regionCode: string;
regionCode тоже может быть nil в Swift.

2021-04-12 10:51 UTC, ren6 commented on src/ApphudSdkType.ts
> +  status: string;
вроде бы subscription status - это integer поле, когда вызывается `subscription.status.rawValue`. Тут норм ли все будет каститься?

2021-04-12 10:51 UTC, ren6 commented on src/ApphudSdkType.ts
> +  cancelledAt: string;
а nullable поля не нужно с вопросительным знаком писать? Почему иногда стоит вопросительный знак, иногда нет?

2021-04-13 05:46 UTC, alexandr-makarov-am commented on src/ApphudSdkType.ts
> +export interface AttributeProperties {
Переименовано

2021-04-13 05:46 UTC, alexandr-makarov-am commented on src/ApphudSdkType.ts
> +  regionCode: string;
Исправлено

2021-04-13 05:46 UTC, alexandr-makarov-am commented on src/ApphudSdkType.ts
> +  status: string;
Да, тут все норм будет

2021-04-13 05:46 UTC, alexandr-makarov-am commented on src/ApphudSdkType.ts
> +  cancelledAt: string;
Да, верно, исправил. Эти поля могут быть необязательными

2021-04-13 09:44 UTC, ren6 requested changes

2021-04-13 09:44 UTC, ren6 commented on src/ApphudSdkType.ts
> +  canceledAt: string;
canceledAt  должно быть optional

2021-04-13 09:44 UTC, ren6 commented on src/ApphudSdkType.ts
> +export interface ApphudSubscriptionStatus {
не понимаю, это что за структура? Должна быть только ApphudSubscription

2021-04-13 09:44 UTC, ren6 commented on src/ApphudSdkType.ts
> +  productId?: string;
productId, expiresAt, startedAt, isInRetryBilling, isAutoRenewEnabled, isIntroductoryActivated - не должны быть optional.
Только cancelledAt?

2021-04-13 09:44 UTC, ren6 commented on src/ApphudSdkType.ts
> +  subscription(): Promise<ApphudSubscriptionStatus>;
ApphudSubscription должен быть, структуры ApphudSubscriptionStatus не должно существовать.
ApphudSubscriptionStatus - это всего лишь enum для поля status.
https://github.com/apphud/ApphudSDK-Android/blob/master/sdk/src/main/java/com/apphud/sdk/domain/ApphudSubscriptionStatus.kt

и 

https://github.com/apphud/ApphudSDK/blob/master/ApphudSDK/ApphudSubscription.swift#L23

2021-04-13 11:47 UTC, alexandr-makarov-am commented on src/ApphudSdkType.ts
> +  subscription(): Promise<ApphudSubscriptionStatus>;
Это внутрення структура, потому как напрямую с реакт натив передать значение enum невозможно, Но можно передать string и восстановить значение enum

2021-04-13 11:47 UTC, alexandr-makarov-am commented on src/ApphudSdkType.ts
> +export interface ApphudSubscriptionStatus {
Это внутренняя структура, определяющая список возможных значений enum

2021-04-13 12:11 UTC, alexandr-makarov-am commented on src/ApphudSdkType.ts
> +  productId?: string;
https://gyazo.com/c1040c87e0367235183751f6a0061551 cогласно кода, это так

2021-04-14 13:12 UTC, ren6 commented on src/ApphudSdkType.ts
> +export interface ApphudSubscriptionStatus {
да, но почему тут описывается структура подписки? productId, expiresDate и тд
чето не понимаю.

2021-04-15 09:04 UTC, ren6 requested changes

2021-04-15 09:48 UTC, alexandr-makarov-am commented on ios/ApphudSdk.swift
> +                "nonRenewingPurchase": DataTransformer.nonRenewingPurchase(nonRenewingPurchase: result.nonRenewingPurchase!),
Исправил

2021-04-19 11:23 UTC, merged