feat: created changes for skproduct
apphud/ApphudSDK-React-Native pull request #47
Opened 2022-10-25 07:45 UTC by alexandr-makarov-am

2022-10-25 11:36 UTC, ren6 requested changes

2022-10-27 08:28 UTC, alexandr-makarov-am commented on ios/DataTransformer.swift
> +        "downloadContentVersion": downloadContentVersion
Исправлено

2022-10-27 08:28 UTC, alexandr-makarov-am commented on ios/DataTransformer.swift
> +        "price": price.description,
Исправлено

2022-10-27 08:28 UTC, alexandr-makarov-am commented on ios/DataTransformer.swift
> +        "currencyCode": currencyCode ?? ""
Исправлено

2022-10-27 08:28 UTC, alexandr-makarov-am commented on ios/DataTransformer.swift
> +        "price": price.description,
Исправлено

2022-10-31 09:36 UTC, merged