feat: implemented paywals
apphud/ApphudSDK-React-Native pull request #58
Opened 2023-04-17 13:31 UTC by alexandr-makarov-am

2023-05-10 08:24 UTC, ren6 requested changes

2023-05-10 08:24 UTC, ren6 commented on ios/DataTransformer.swift
> +            "sku_details": skProduct
лучше давай назовем product

2023-05-10 08:24 UTC, ren6 commented on ios/DataTransformer.swift
> +            "sku_details": skProduct
и почему где-то camel case, где-то snake case ?
в мобилках принято camelCase

2023-05-10 08:24 UTC, ren6 commented on android/src/main/java/com/reactnativeapphudsdk/ApphudDataTransformer.kt
> +      payload.putString("paywall_identifier", apphudProduct.paywall_identifier);
давай везде одинаковый camelCase

2023-05-16 05:17 UTC, alexandr-makarov-am commented on android/src/main/java/com/reactnativeapphudsdk/ApphudDataTransformer.kt
> +      payload.putString("priceAmountMicros", skuDetails.priceAmountMicros.toString());
Потому что priceAmountMicros имеет LONG тип. А передать возможно только INT либо String. Что-бы исключить потерю части битов, я применил приведение в string

2023-05-16 05:18 UTC, alexandr-makarov-am commented on android/src/main/java/com/reactnativeapphudsdk/ApphudDataTransformer.kt
> +      payload.putString("introductoryPrice", skuDetails.freeTrialPeriod);
https://gyazo.com/4fdcebfd2b06e460b8342c301ee27c2c такой параметр есть

2023-05-16 05:20 UTC, alexandr-makarov-am commented on android/src/main/java/com/reactnativeapphudsdk/ApphudDataTransformer.kt
> +      payload.putString("paywall_identifier", apphudProduct.paywall_identifier);
исправил

2023-05-16 05:20 UTC, alexandr-makarov-am commented on ios/DataTransformer.swift
> +            "sku_details": skProduct
исправил

2023-05-16 10:06 UTC, ren6 commented on android/src/main/java/com/reactnativeapphudsdk/ApphudDataTransformer.kt
> +      payload.putString("introductoryPrice", skuDetails.freeTrialPeriod);
нет, я про то что на 37 и 38 строчке одинаково. исправить надо

2023-05-16 10:08 UTC, ren6 commented on android/src/main/java/com/reactnativeapphudsdk/ApphudDataTransformer.kt
> +      payload.putString("priceAmountMicros", skuDetails.priceAmountMicros.toString());
@alexandr-makarov-am а можеш добавить еще formattedPrice? вроде что-то такое должно быть

2023-05-16 10:10 UTC, ren6 commented on android/src/main/java/com/reactnativeapphudsdk/ApphudDataTransformer.kt
> +      result.putString("json",paywall.json.toString());
а можно ли json в виде nativeMap отдавать? там тоже ключ-значение отдается.

2023-05-16 10:15 UTC, ren6 commented on android/src/main/java/com/reactnativeapphudsdk/ApphudDataTransformer.kt
> +      payload.putMap("product", apphudProduct.skuDetails?.let { getSkuDetailsMap(it) });
а, или это только для андроида

2023-05-17 09:42 UTC, alexandr-makarov-am commented on android/src/main/java/com/reactnativeapphudsdk/ApphudDataTransformer.kt
> +      payload.putMap("product", apphudProduct.skuDetails?.let { getSkuDetailsMap(it) });
Это только для android

2023-05-18 06:11 UTC, alexandr-makarov-am commented on android/src/main/java/com/reactnativeapphudsdk/ApphudDataTransformer.kt
> +      result.putString("json",paywall.json.toString());
Да можно, но это не принципиально, на JS стороне JSON будет десереализован и получится объект

2023-05-18 06:13 UTC, alexandr-makarov-am commented on ios/DataTransformer.swift
> +            "product_id": productId,
поправил

2023-05-22 04:22 UTC, ren6 commented on android/src/main/java/com/reactnativeapphudsdk/ApphudSdkModule.kt
> +    fun optOutOfTracking(promise: Promise) {
этот метод должен быть и в iOS и в Android

2023-05-22 04:28 UTC, ren6 commented on ios/ApphudSdk.swift
> +    func submitPushNotificationsToken(token:Data,  resolve: @escaping RCTPromiseResolveBlock, reject: @escaping RCTPromiseRejectBlock) {
этот метод точно будет работать? Data принимает, а не String

2023-05-23 05:45 UTC, alexandr-makarov-am commented on android/src/main/java/com/reactnativeapphudsdk/ApphudDataTransformer.kt
> +      payload.putString("priceAmountMicros", skuDetails.priceAmountMicros.toString());
formattedPrice не нашел https://gyazo.com/e7aff667d07bf2f52dbd193eca226e35

2023-05-23 05:46 UTC, alexandr-makarov-am commented on ios/ApphudSdk.swift
> +    func submitPushNotificationsToken(token:Data,  resolve: @escaping RCTPromiseResolveBlock, reject: @escaping RCTPromiseRejectBlock) {
исправил

2023-05-23 09:48 UTC, ren6 commented on android/src/main/java/com/reactnativeapphudsdk/ApphudDataTransformer.kt
> +      payload.putString("priceAmountMicros", skuDetails.priceAmountMicros.toString());
а, это и есть originalPrice оказывается

2023-05-24 12:07 UTC, merged